baseURL = "/"
languageCode = "en-us"
title = "Kyverno"
theme = ["docsy"]
description = "Kyverno is a policy engine designed for Kubernetes"
Paginate = 20

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

ignoreFiles = [ "^OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$"]

timeout = 3000

# Norwegian ("no") is sometimes but not currently used for testing.
# Hindi is disabled because it's currently in development.
disableLanguages = ["hi", "no"]

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = ""

[outputs]
  home = ["HTML","RSS","JSON"]

# Add your release versions here

[[params.versions]]
  version = "v1.4.2"
  url = "https://kyverno.io"

[[params.versions]]
  version = "v1.4.1"
  url = "https://release-1-4-1.kyverno.io"
