## Configuration for goldmark markdown parser: https://gohugo.io/getting-started/configuration-markup#goldmark
[goldmark]
  [goldmark.renderer]
    unsafe = true
[highlight]
  # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
  style = "tango"
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = false
  tabWidth = 2
  # Uncomment if you want your chosen highlight style used for code blocks without a specified language
  # guessSyntax = "true"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
# [blackfriday]
# plainIDAnchors = true
# hrefTargetBlank = true
# angledQuotes = false
# latexDashes = true

# Highlighting config
# pygmentsCodeFences = true
# pygmentsUseClasses = false
# # Use the new Chroma Go highlighter in Hugo.
# pygmentsUseClassic = false
# #pygmentsOptions = "linenos=table"
# # See https://help.farbox.com/pygments.html
# pygmentsStyle = "emacs"
