# Everything below this are Site Params
copyright = "The Kyverno Authors"
policies = ["generate", "mutate", "validate", "verifyImages", "cleanUp"]
# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 0 # to enable function set >= 1

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
showLineNumbers = false

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [versions] set.
version_menu = "v1.12.0"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "v1.12.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://main.kyverno.io"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/kyverno/website"
github_branch = "main"

# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/kyverno/kyverno"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "016003b0b44d00772"

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 02, 2006 at 3:04 PM PST"

[mermaid]
enable = true

[[policyFilters]]
title = "Policy Type"
filterID = "policytype"
isFixed = true
weight = 1

[[policyFilters]]
title = "Policy Category"
filterID = "category"
weight = 2

[[policyFilters]]
title = "Minimum Version" # title on the UI
filterID = "version" # key you used inside index.json
weight = 3

[[policyFilters]]
title = "Subject" # title on the UI
filterID = "subject" # key you used inside index.json
weight = 4

# User interface configuration
[ui]

# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true

#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false

#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true

#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false

# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[ui.feedback]
enable = true

# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/kyverno/kyverno/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/kyverno/website/issues/new/choose">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[ui.readingtime]
enable = false

[links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.

[[links.user]]
	name ="Kyverno GitHub repository"
	url = "https://github.com/kyverno/kyverno/"
	icon = "fab fa-github"
  desc = "Kyverno GitHub"
[[links.user]]
	name ="Follow Kyverno on Twitter"
	url = "https://twitter.com/kyverno"
	icon = "fab fa-twitter"
  desc = "Follow Kyverno on Twitter for the latest news!"
[[links.user]]
	name = "Kyverno channel on the Kubernetes slack"
	url = "https://slack.k8s.io/#kyverno"
	icon = "fab fa-slack"
  desc = "Kyverno channel on the Kubernetes slack"
[[links.user]]
	name = "Kyverno mailing list"
	url = "https://groups.google.com/g/kyverno"
	icon = "fa fa-envelope"
  desc = "Kyverno mailing list"

[pushAssets]
css = [
  "callouts",
  "styles"
]

js = [
  "script"
]

# version_menu = "Versions"
# Add your release versions here
[[versions]]
  version = "v1.12.0"
  url = "https://kyverno.io"

[[versions]]
  version = "v1.11.0"
  url = "https://release-1-11-0.kyverno.io"

[[versions]]
  version = "v1.10.0"
  url = "https://release-1-10-0.kyverno.io"

[[versions]]
  version = "v1.9.0"
  url = "https://release-1-9-0.kyverno.io"

[[versions]]
  version = "main"
  url = "https://main.kyverno.io"
