baseURL = "/"
languageCode = "en-us"
title = "Kyverno"
theme = ["docsy"]
description = "Kyverno is a policy engine designed for Kubernetes"
Paginate = 20

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

ignoreFiles = [ "^OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$"]

timeout = 3000

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "emacs"

# Norwegian ("no") is sometimes but not currently used for testing.
# Hindi is disabled because it's currently in development.
disableLanguages = ["hi", "no"]

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"


# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Top-level navigation (horizontal)

[[menu.main]]
    name = "About Kyverno"
    weight = -103
    url = "#td-block-1"
[[menu.main]]
    name = "Documentation"
    weight = -102
    url = "/docs"
[[menu.main]]
    name = "Policies"
    weight = -101
    url = "/policies"
[[menu.main]]
    name = "GitHub"
    weight = -100
    url = "https://github.com/kyverno/kyverno/"
[[menu.main]]
    name = "Resources"
    weight = -99
    url = "/resources"


[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = ""

# Language configuration

[languages]
[languages.en]
title = "Kyverno"
description = "Kyverno is a policy engine designed for Kubernetes"
languageName ="English"

# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

[params]
    copyright = "The Kyverno Authors"

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://kyverno.io"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/kyverno/website"
github_branch = "main"

# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/kyverno/kyverno"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "016003b0b44d00772"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]

# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true

#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false

#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true

#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false

# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true

# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/kyverno/kyverno/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/kyverno/kyverno/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.

[[params.links.user]]
	name ="Follow Kyverno on Twitter"
	url = "https://twitter.com/kyverno"
	icon = "fab fa-twitter"
        desc = "Follow Kyverno on Twitter for the latest news!"
[[params.links.user]]
	name = "Kyverno slack channel"
	url = "https://kubernetes.slack.com/"
	icon = "fab fa-slack"
        desc = "Kyverno slack channel"
[[params.links.user]]
	name = "Kyverno mailing list"
	url = "https://groups.google.com/g/kyverno"
	icon = "fa fa-envelope"
        desc = "Kyverno mailing list"

version_menu = "Versions"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 02, 2006 at 3:04 PM PST"

[params.pushAssets]
css = [
    "callouts",
    "styles"
]

js = [
    "script"
]
