name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.6.0
        with:
          hugo-version: latest
          extended: true

      - name: npm install
        run: npm install --save-dev autoprefixer && npm install --save-dev postcss-cli && npm install -D postcss

      - name: Build
        run: hugo --minify

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a # v1.9.3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail: true
          debug: false
          args: --verbose --no-progress -E 'public'

      # - name: Create Issue From File
      #   if: steps.lychee.outputs.exit_code != 0
      #   uses: peter-evans/create-issue-from-file@v3
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue