name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Check unrendered links
        id: lychee_unrendered
        uses: lycheeverse/lychee-action@7da8ec1fc4e01b5a12062ac6c589c10a4ce70d67 # v2.0.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail: true
          debug: false
          args: --no-progress --include-fragments --github-token ${{secrets.GITHUB_TOKEN}} --config config/lychee.toml -E content/

      # Deactivated. The --include-fragments flag is causing failures because rendered links
      # have a trailing '#' which is probably a result of the link style change plus the new
      # custom link renderer in layouts/_default/_markup_render-link.html.

      # - name: Setup Hugo
      #   uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.6.0
      #   with:
      #     hugo-version: latest
      #     extended: true

      # - name: Waiting for Netlify Preview
      #   uses: jakepartusch/wait-for-netlify-action@f1e137043864b9ab9034ae3a5adc1c108e3f1a48 # v1.4
      #   id: wait-for-netflify-preview
      #   with:
      #     site_name: kyverno
      #     max_timeout: 120

      # - name: Install site dependencies
      #   run: npm install --save-dev autoprefixer && npm install --save-dev postcss-cli && npm install -D postcss

      # - name: Build site with Hugo
      #   run: hugo --minify -b ${{ steps.wait-for-netflify-preview.outputs.url }}

      # - name: Check rendered links
      #   id: lychee_rendered
      #   uses: lycheeverse/lychee-action@7da8ec1fc4e01b5a12062ac6c589c10a4ce70d67 # v2.0.0
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     fail: true
      #     debug: false
      #     args: --no-progress --include-fragments --github-token ${{secrets.GITHUB_TOKEN}} -c lychee.toml -E public

      # - name: Create Issue From File
      #   if: steps.lychee.outputs.exit_code != 0
      #   uses: peter-evans/create-issue-from-file@v3
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue