# # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# TODO: Re-enable this workflow once we have the basis for the website
# name: Verify codegen

# permissions: {}

# on:
#   pull_request:
#     branches:
#       - astro

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   verify-codegen:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
#       - name: Install go
#         uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
#         with:
#           go-version-file: render/go.mod
#       - name: Verify generated code is up to date
#         run: make verify-codegen
